spring.application.name=kanban-board
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret

# Performance
spring.threads.virtual.enabled=true
spring.sql.init.mode=always